### ISSUE TITLE
Ideal time for prometheus scrape_interval

### ISSUE THREAD

**Issue by Adhira-Deogade** [draganm/missing-container-metrics#3]
There are a lot of metrics generated, do you know what's the ideal time needed to be set to avoid prometheus to crash while pulling a bunch of these metrics? Thanks

**Comment by draganm** [comment]
It is very difficult to estimate this number, since it's a multi dimensional problem - variables are number of containers deployed at a time, memory limit and version of Prometheus. Probably doing some kind of experiment is the fastest way to get there. One thing to keep in mind is:
https://github.com/draganm/missing-container-metrics/blob/master/event_handler.go#L118

When a container is deleted, it's metric will linger around for 5 minutes, so your scraping interval should not be longer than that!

**Comment by Adhira-Deogade** [comment]
Agree,
